### ISSUE TITLE
I want to see _.compose insted of _.chain

### ISSUE THREAD

**Issue by SiarheiMelnik** [21-23/qd-platform#27]
Hi,
Thank you for lodash _qd.
But I think you need to replace `_.chain` by `_.compose`, because using `_.chain` is a mistake.

https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba

Thank you

**Comment by kirilknysh** [comment]
![image](https://user-images.githubusercontent.com/3236551/33335329-068e8ac4-d46d-11e7-92c6-e4a6662c911c.png)
